// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLs-ST5mY0hSOeqo93eAfoV1a04QDShPA',
    appId: '1:381082995476:web:31c63ea53aabb3f7999001',
    messagingSenderId: '381082995476',
    projectId: 'bridella-eb876',
    authDomain: 'bridella-eb876.firebaseapp.com',
    storageBucket: 'bridella-eb876.appspot.com',
    measurementId: 'G-JVHM7ZG26P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKGA4jYLyrFycRfKnOizxab8Y0onuQ7ME',
    appId: '1:381082995476:android:7462564cac606b52999001',
    messagingSenderId: '381082995476',
    projectId: 'bridella-eb876',
    storageBucket: 'bridella-eb876.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFVVL_8Q-sjFivty1CLjrXPOiCl6TO1G8',
    appId: '1:381082995476:ios:e7739bbcf11e18fe999001',
    messagingSenderId: '381082995476',
    projectId: 'bridella-eb876',
    storageBucket: 'bridella-eb876.appspot.com',
    iosClientId: '381082995476-l5gctt32shq6mvnnhf0ms265lderr5fq.apps.googleusercontent.com',
    iosBundleId: 'com.example.bridella',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFVVL_8Q-sjFivty1CLjrXPOiCl6TO1G8',
    appId: '1:381082995476:ios:e7739bbcf11e18fe999001',
    messagingSenderId: '381082995476',
    projectId: 'bridella-eb876',
    storageBucket: 'bridella-eb876.appspot.com',
    iosClientId: '381082995476-l5gctt32shq6mvnnhf0ms265lderr5fq.apps.googleusercontent.com',
    iosBundleId: 'com.example.bridella',
  );
}
